BOARD=orangepi5pro
BRANCH=edge
RELEASE=resolute

BUILD_MINIMAL=no
BUILD_DESKTOP=no
KERNEL_CONFIGURE=no
EXPERT=yes

ROOTFS_TYPE=ext4
COMPRESS_OUTPUTIMAGE=img
NETWORKING_STACK=network-manager

enable_extension "opi-native"
