say "Resolving and validating component sources"
require_github_tag anomalyco/opencode "$OPENCODE_TAG"; OPENCODE_URL="https://github.com/anomalyco/opencode/releases/download/${OPENCODE_TAG}/opencode-linux-arm64.tar.gz"; require_download_url "$OPENCODE_URL" "OpenCode ${OPENCODE_TAG} ARM64 tarball"
for spec in "moonlight-stream/moonlight-qt:$MOONLIGHT_TAG" "flyinghead/flycast:$FLYCAST_TAG" "melonDS-emu/melonDS:$MELONDS_TAG" "azahar-emu/azahar:$AZAHAR_TAG" "hrydgard/ppsspp:$PPSSPP_TAG" "Rosalie241/RMG:$RMG_TAG" "snes9xgit/snes9x:$SNES9X_TAG" "Stremio/stremio-linux-shell:$STREMIO_TAG" "mpv-player/mpv:$MPV_TAG"; do require_github_tag "${spec%%:*}" "${spec#*:}"; done
require_github_commit 0x90shell/gamepad-osk "$GAMEPAD_OSK_COMMIT"
ESDE_REPO="es-de/emulationstation-de"; require_gitlab_tag "$ESDE_REPO" "$ESDE_TAG"; ESDE_COMMIT="$(remote_tag_commit "https://gitlab.com/${ESDE_REPO}.git" "$ESDE_TAG")"; [[ "$ESDE_COMMIT" =~ ^[0-9a-f]{40}$ ]] || die "Unable to resolve ES-DE commit for ${ESDE_TAG} via Git transport"
github_content_exists hrydgard/ppsspp "$PPSSPP_TAG" CMakeLists.txt; github_content_exists moonlight-stream/moonlight-qt "$MOONLIGHT_TAG" moonlight-qt.pro; github_content_exists Rosalie241/RMG "$RMG_TAG" CMakeLists.txt; github_content_exists flyinghead/flycast "$FLYCAST_TAG" CMakeLists.txt; github_content_exists melonDS-emu/melonDS "$MELONDS_TAG" CMakeLists.txt; github_content_exists azahar-emu/azahar "$AZAHAR_TAG" CMakeLists.txt; github_content_exists snes9xgit/snes9x "$SNES9X_TAG" gtk/CMakeLists.txt; github_content_exists 0x90shell/gamepad-osk "$GAMEPAD_OSK_COMMIT" go.mod; github_content_exists 0x90shell/gamepad-osk "$GAMEPAD_OSK_COMMIT" config.example; github_content_exists 0x90shell/gamepad-osk "$GAMEPAD_OSK_COMMIT" gamepad-osk.udev; github_content_exists Stremio/stremio-linux-shell "$STREMIO_TAG" Cargo.toml; github_content_exists Stremio/stremio-linux-shell "$STREMIO_TAG" Cargo.lock; github_content_exists Stremio/stremio-linux-shell "$STREMIO_TAG" data/server.js; github_content_exists Stremio/stremio-linux-shell "$STREMIO_TAG" data/com.stremio.Stremio.gschema.xml; github_content_exists mpv-player/mpv "$MPV_TAG" meson.build
STREMIO_CARGO_RAW="https://raw.githubusercontent.com/Stremio/stremio-linux-shell/${STREMIO_TAG}/Cargo.toml"; require_url_contains "$STREMIO_CARGO_RAW" 'v4_22' "Stremio GTK >= 4.22 feature requirement"; require_url_contains "$STREMIO_CARGO_RAW" 'v1_9' "Stremio libadwaita >= 1.9 feature requirement"; require_url_contains "$STREMIO_CARGO_RAW" 'v2_52' "Stremio WebKitGTK >= 2.52 feature requirement"
require_url_contains "https://gitlab.com/es-de/emulationstation-de/-/raw/${ESDE_TAG}/CMakeLists.txt" 'VIDEO_HW_DECODING|DEINIT_ON_LAUNCH' "ES-DE CMake options"; require_url_contains "https://raw.githubusercontent.com/hrydgard/ppsspp/${PPSSPP_TAG}/CMakeLists.txt" 'PPSSPPSDL' "PPSSPP SDL target"; require_url_contains "https://raw.githubusercontent.com/azahar-emu/azahar/${AZAHAR_TAG}/CMakeLists.txt" 'ENABLE_VULKAN' "Azahar Vulkan option"
V4L2_FFMPEG_REPO="https://code.ffmpeg.org/Kwiboo/FFmpeg.git"; V4L2_FFMPEG_COMMIT="$(remote_branch_commit "$V4L2_FFMPEG_REPO" "$V4L2_FFMPEG_BRANCH")"; if [[ ! "$V4L2_FFMPEG_COMMIT" =~ ^[0-9a-f]{40}$ ]]; then V4L2_FFMPEG_REPO="https://github.com/Kwiboo/FFmpeg.git"; V4L2_FFMPEG_COMMIT="$(remote_branch_commit "$V4L2_FFMPEG_REPO" "$V4L2_FFMPEG_BRANCH")"; fi; [[ "$V4L2_FFMPEG_COMMIT" =~ ^[0-9a-f]{40}$ ]] || die "Unable to resolve ${V4L2_FFMPEG_BRANCH} from either Kwiboo FFmpeg remote"
DUCK_TAG=latest; DUCK_URL="https://github.com/stenzek/duckstation/releases/download/latest/DuckStation-arm64.AppImage"; require_download_url "$DUCK_URL" "DuckStation ARM64 AppImage"
require_github_tag ARMSX2/ARMSX2 "$ARMSX2_TAG"; ARMSX2_COMMIT="$(remote_tag_commit "https://github.com/ARMSX2/ARMSX2.git" "$ARMSX2_TAG")"; [[ "$ARMSX2_COMMIT" =~ ^[0-9a-f]{40}$ ]] || die "Unable to resolve ARMSX2 ${ARMSX2_TAG} commit"; ARMSX2_DATE="${ARMSX2_TAG#nightly-}"; [[ "$ARMSX2_DATE" =~ ^[0-9]{8}$ ]] || die "Unexpected ARMSX2 nightly tag format: ${ARMSX2_TAG}"; ARMSX2_SHORT="${ARMSX2_COMMIT:0:10}"; ARMSX2_ASSET="ARMSX2-nightly-${ARMSX2_DATE}-${ARMSX2_SHORT}-Linux-arm64-4K-pages.AppImage"; ARMSX2_URL="https://github.com/ARMSX2/ARMSX2/releases/download/${ARMSX2_TAG}/${ARMSX2_ASSET}"; require_download_url "$ARMSX2_URL" "ARMSX2 ${ARMSX2_TAG} Linux ARM64 4K AppImage"
GE_TAG="$GE_PROTON_TAG"; GE_URL="https://github.com/GloriousEggroll/proton-ge-custom/releases/download/${GE_TAG}/${GE_TAG}-aarch64.tar.gz"; GE_STATUS="$(head_status "$GE_URL")"; if [[ "$GE_STATUS" != 200 && "$GE_STATUS" != 206 ]]; then warn "Optional GE-Proton seed unavailable (HTTP ${GE_STATUS:-000}); continuing without it"; GE_TAG=""; GE_URL=""; fi
jq -n --arg generated "$(date --iso-8601=seconds)" --arg builder "v${PROFILE_VERSION}-repo" --arg opencode "$OPENCODE_TAG" --arg moonlight "$MOONLIGHT_TAG" --arg esde "$ESDE_TAG" --arg esde_commit "$ESDE_COMMIT" --arg gamepad "$GAMEPAD_OSK_COMMIT" --arg stremio "$STREMIO_TAG" --arg ffmpeg_v4l2 "$V4L2_FFMPEG_BRANCH" --arg ffmpeg_repo "$V4L2_FFMPEG_REPO" --arg ffmpeg_commit "$V4L2_FFMPEG_COMMIT" --arg mpv "$MPV_TAG" --arg rmg "$RMG_TAG" --arg flycast "$FLYCAST_TAG" --arg melonds "$MELONDS_TAG" --arg azahar "$AZAHAR_TAG" --arg snes9x "$SNES9X_TAG" --arg duck "$DUCK_TAG" --arg armsx2 "$ARMSX2_TAG" --arg armsx2_commit "$ARMSX2_COMMIT" --arg ppsspp "$PPSSPP_TAG" --arg ge "$GE_TAG" '{generated:$generated,builder:$builder,target:{board:"orangepi5pro",branch:"edge",release:"resolute",arch:"aarch64"},components:{opencode:$opencode,moonlight:$moonlight,es_de:$esde,es_de_commit:$esde_commit,gamepad_osk_commit:$gamepad,stremio_linux_shell:$stremio,ffmpeg_v4l2_request_branch:$ffmpeg_v4l2,ffmpeg_v4l2_request_repo:$ffmpeg_repo,ffmpeg_v4l2_request_commit:$ffmpeg_commit,mpv:$mpv,rmg:$rmg,flycast:$flycast,melonds:$melonds,azahar:$azahar,snes9x:$snes9x,duckstation:$duck,armsx2:$armsx2,armsx2_commit:$armsx2_commit,ppsspp:$ppsspp,ge_proton:$ge}}' > "$LOCK"
cat "$LOCK"; good "All mandatory source refs and recipe layouts resolve"
install -m0644 "$PROFILE_DIR/packages/base.txt" "$WORK/required-packages.base.txt"
install -m0644 "$PROFILE_DIR/packages/build-groups.txt" "$WORK/build-package-groups.txt"
